### ISSUE TITLE
more subprocess woes

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#206]
@CJ-Wright   Thanks for looking at this.

```
loading ..\db\presentations.yml...
loading ../../rg-db-public/db\groups.yml...
loading ../../rg-db-public/db\institutions.yml...
loading ../../rg-db-public/db\people.yml...
loading ../../rg-db-public/db\projects.yml...
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: dvipdf
Traceback (most recent call last):
  File "C:/Users/simon/Anaconda3/envs/bg/Scripts/regolith", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "C:\Users\simon\dev\regolith\scripts\regolith", line 3, in <module>
    main()
  File "c:\users\simon\dev\regolith\regolith\main.py", line 254, in main
    CONNECTED_COMMANDS[rc.cmd](rc)
  File "c:\users\simon\dev\regolith\regolith\commands.py", line 113, in build
    bldr.build()
  File "c:\users\simon\dev\regolith\regolith\builders\basebuilder.py", line 103, in build
    getattr(self, cmd)()
  File "c:\users\simon\dev\regolith\regolith\builders\preslistbuilder.py", line 239, in latex
    self.pdf(outfile)
  File "c:\users\simon\dev\regolith\regolith\builders\basebuilder.py", line 133, in pdf
    self.run(["dvipdf", base])
  File "c:\users\simon\dev\regolith\regolith\builders\basebuilder.py", line 124, in run
    subprocess.run(cmd, cwd=self.bldir, check=True)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\lib\subprocess.xsh", line 14, in run
    p = ![@(cmd)]
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 19553, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 19516, in run_subproc
    command.end()
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 12724, in end
    self._end(tee_output=tee_output)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 12743, in _end
    self._raise_subproc_error()
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\xonsh\__amalgam__.py", line 12864, in _raise_subproc_error
    output=self.output)
subprocess.CalledProcessError: Command '['dvipdf', 'presentations-bg-cwright']' returned non-zero exit status 1
```

**Comment by sbillinge** [comment]
I use MikTex but not sure how to allow regolith to find it?  Is there some
kind of tex path that needs to be set up?

**Comment by CJ-Wright** [comment]
What is the command you run for building PDFs?

**Comment by sbillinge** [comment]
either latex or pdflatex works, though I generally build from my winedt IDE

**Comment by CJ-Wright** [comment]
The current command sequence is:
```python
self.run(["latex"] + LATEX_OPTS + [base + ".tex"])
self.run(["bibtex"] + [base + ".aux"])
self.run(["latex"] + LATEX_OPTS + [base + ".tex"])
self.run(["latex"] + LATEX_OPTS + [base + ".tex"])
self.run(["dvipdf", base])
```
Maybe we can provide the option to run pdflatex?
@scopatz thoughts?

**Comment by sbillinge** [comment]
I have ``dvips`` which could then be converted to pdf with ``ps2pdf``, or
we could just replace ``latex`` with ``pdflatex`` and remove the
``dvipdf```?  Not sure the downsides to that but it would work for me
then.....

**Comment by CJ-Wright** [comment]
I think we can inspect for windows and run pdflatex as the last command.

**Comment by sbillinge** [comment]
sounds good.  It may not be a windows thing per-se, it is my particular
setup.  But I think my setup is some kind of more or less standard MikTex
installation which is very common for windows users, so this could probably
work.

S
