### ISSUE TITLE
BUG: u_milestones unexpected crash

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#544]
I got this crash but I don't think it should have happenned.  Pls could you take a look? 
```
$ rh u_milestone 20sb_shortcourse
loading ..\../rg-db-private/db\projecta.yml...
loading ..\../rg-db-group/db\projecta.yml...
dumping projecta...
dumping projecta...
Please choose from one of the following to update/add:
1. new milestone
2. kickoff    due date: 2020-05-24    status: finished
3. send trial video to Liam for first lecture    due date: 2020-07-07    status: converged
4. complete videos    due date: 2020-07-07    status: converged
5. deliverable    due date: 2021-07-12    status: proposed
(bg)
simon@LAPTOP-FU6OME5O MINGW64 ~/dbs/rg-db-private/local (master)
$ rh u_milestone 20sb_shortcourse -i 3 -s f
loading ..\../rg-db-private/db\projecta.yml...
loading ..\../rg-db-group/db\projecta.yml...
Traceback (most recent call last):
  File "C:/Users/simon/Anaconda3/envs/bg/Scripts/regolith", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "C:\Users\simon\dev\regolith\scripts\regolith", line 3, in <module>
    main()
  File "c:\users\simon\dev\regolith\regolith\main.py", line 336, in main
    CONNECTED_COMMANDS[rc.cmd](rc)
  File "c:\users\simon\dev\regolith\regolith\commands.py", line 150, in helper
    hlpr.hlp()
  File "c:\users\simon\dev\regolith\regolith\helpers\basehelper.py", line 93, in hlp
    getattr(self, cmd)()
  File "c:\users\simon\dev\regolith\regolith\helpers\u_milestonehelper.py", line 164, in db_updater
    raise RuntimeError(f"please rerun specifying --type with a value from {ALLOWED_TYPES}")
RuntimeError: please rerun specifying --type with a value from {'m': 'meeting', 'r': 'release', 'p': 'pull request', 'o': 'other'}
```

**Comment by dy2403** [comment]
Hi @sbillinge,
I think this happened because I made it request a type when there is not a type already in the database. Thus, to run it properly, when you receive this error, you need to also give a type. I can change that if you like to!
You requested me to add this, because you wanted to make type required.

**Comment by sbillinge** [comment]
OK, I see.  I think we need a more informational crash message that says, more or less, what you said in the comment above....  Could you have a crack at it?  Thx.  This should go away in due course if people start using helpers to make prums and milestones.  Pls could you check for me that a_projectum does insert a type by default.  Thx.
