### ISSUE TITLE
Error building ergs website with regolith master

### ISSUE THREAD

**Issue by asmeurer** [regro/regolith#65]
```
loading _build/_dbs/ergs-public/db/blog.yaml...
loading _build/_dbs/ergs-public/db/citations.yaml...
loading _build/_dbs/ergs-public/db/grants.yaml...
loading _build/_dbs/ergs-public/db/jobs.yaml...
loading _build/_dbs/ergs-public/db/news.yaml...
loading _build/_dbs/ergs-public/db/people.yaml...
loading _build/_dbs/ergs-public/db/projects.yaml...
dumping jobs...
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/bin/regolith", line 3, in <module>
    main()
  File "/Users/aaronmeurer/Documents/regolith/regolith/main.py", line 184, in main
    CONNECTED_COMMANDS[rc.cmd](rc)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/Users/aaronmeurer/Documents/regolith/regolith/database.py", line 126, in connect
    dump_database(db, client, rc)
  File "/Users/aaronmeurer/Documents/regolith/regolith/database.py", line 111, in dump_database
    dump_git_database(db, client, rc)
  File "/Users/aaronmeurer/Documents/regolith/regolith/database.py", line 74, in dump_git_database
    to_add = client.dump_database(db)
  File "/Users/aaronmeurer/Documents/regolith/regolith/fsclient.py", line 142, in dump_database
    filename = self.dump_yaml(collection, collname, dbpath)
  File "/Users/aaronmeurer/Documents/regolith/regolith/fsclient.py", line 127, in dump_yaml
    dump_yaml(f, docs, inst=inst)
  File "/Users/aaronmeurer/Documents/regolith/regolith/fsclient.py", line 50, in dump_yaml
    inst.indent(mapping=2, sequence=4, offset=2)
TypeError: 'NoneType' object is not callable
```

**Comment by asmeurer** [comment]
Seems to be an issue with older versions of ruamel.
