### ISSUE TITLE
u_milestone bug

### ISSUE THREAD

**Issue by connorjbracy** [regro/regolith#790]
Attempting to run u_milestone with fields:
`$ helper_gui --ignore-gooey u_milestone -i 4 --notes "(x) Merge PR containing CI config files""(x) Meet with sbillinge to present/go through the setup process" -- cb_ci_for_getx3`

on `rg-db-group - commit db4217d9a8919728918e9134739e1969a552af10`

produces the following error

```
The milestone Write Setup Instructions for Setting Up CI on pdfgetx3 has been marked as finished in prum cb_ci_for_getx3
Traceback (most recent call last):
  File "~/anaconda3/envs/regolith_env/bin/helper_gui", line 4, in <module>
    __import__('pkg_resources').run_script('regolith==0.5.1', 'helper_gui')
  File "~/anaconda3/envs/regolith_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "~/anaconda3/envs/regolith_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "~/anaconda3/envs/regolith_env/lib/python3.7/site-packages/regolith-0.5.1-py3.7.egg/EGG-INFO/scripts/helper_gui", line 3, in <module>
    main()
  File "~/anaconda3/envs/regolith_env/lib/python3.7/site-packages/regolith-0.5.1-py3.7.egg/regolith/helper_gui_main.py", line 68, in main
    CONNECTED_COMMANDS[rc.cmd](rc)
  File "~/anaconda3/envs/regolith_env/lib/python3.7/site-packages/regolith-0.5.1-py3.7.egg/regolith/commands.py", line 150, in helper
    hlpr.hlp()
  File "~/anaconda3/envs/regolith_env/lib/python3.7/site-packages/regolith-0.5.1-py3.7.egg/regolith/helpers/basehelper.py", line 92, in hlp
    getattr(self, cmd)()
  File "~/anaconda3/envs/regolith_env/lib/python3.7/site-packages/regolith-0.5.1-py3.7.egg/regolith/helpers/u_milestonehelper.py", line 272, in db_updater
    pdoc[identifier].pop('identifier', None)
TypeError: pop() takes at most 1 argument (2 given)
```

**Comment by sbillinge** [comment]
closed by #805
