### ISSUE TITLE
crash on loading projects in regolith app

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#87]
```python
Traceback (most recent call last):
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\regolith\app.py", line 119, in collection_page
    collname=collname, coll=coll, json=json, min=min)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\site-packages\regolith\templates\collection.html", line 31, in top-level template code
    {% set docdump = json.dumps(doc, sort_keys=True, indent=1) %}
  File "C:\Users\simon\Anaconda3\envs\bg\lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\json\encoder.py", line 200, in encode
    chunks = list(chunks)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\json\encoder.py", line 436, in _iterencode
    o = _default(o)
  File "C:\Users\simon\Anaconda3\envs\bg\lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ChainMap(CommentedMap([('description', 'Searching for Metallic Glasses in combinatorial alloys'), ('grant', 'dmref15'), ('name', 'Combinatorial Metallic Glasses'), ('start_date', '2008-01-01'), ('team', [CommentedMap([('begin_year', 2017), ('name', 'cwright'), ('position', 'lgm')]), CommentedMap([('begin_year', 2017), ('name', 'jhattricksimpers'), ('position', 'collpi')])]), ('activities', None), ('deliverables', None), ('_id', '18cw_bmgs')])) is not JSON serializable
```

**Comment by CJ-Wright** [comment]
Thank you for reporting!
This seems to be an issue with interfacing jinja2 with the ChainMap/ChainDB.

**Comment by CJ-Wright** [comment]
Maybe make into a dict before passing into jinja2?
